In [5]:
# As usual, a bit of setup
from __future__ import print_function
import time
import numpy as np
import matplotlib.pyplot as plt
import q3_word2vec

%matplotlib inline

# for auto-reloading external modules
# see http://stackoverflow.com/questions/1907993/autoreload-of-modules-in-ipython
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


# Row Normalize

Normalization is x / sqrt(sum(x ** 2))

In [76]:
q3_word2vec.test_normalize_rows()

Testing normalizeRows...
[[ 0.6         0.8       ]
 [ 0.4472136   0.89442719]]



In [77]:
q3_word2vec.test_word2vec()

==== Gradient check for skip-gram ====
[[-0.96735714 -0.02182641  0.25247529]
 [ 0.73663029 -0.48088687 -0.47552459]
 [-0.27323645  0.12538062  0.95374082]
 [-0.56713774 -0.27178229 -0.77748902]
 [-0.59609459  0.7795666   0.19221644]]
[[-0.6831809  -0.04200519  0.72904007]
 [ 0.18289107  0.76098587 -0.62245591]
 [-0.61517874  0.5147624  -0.59713884]
 [-0.33867074 -0.80966534 -0.47931635]
 [-0.52629529 -0.78190408  0.33412466]]
[[-0.96735714 -0.02182641  0.25247529]
 [ 0.73663029 -0.48088687 -0.47552459]
 [-0.27323645  0.12538062  0.95374082]
 [-0.56713774 -0.27178229 -0.77748902]
 [-0.59609459  0.7795666   0.19221644]]
[[-0.6831809  -0.04200519  0.72904007]
 [ 0.18289107  0.76098587 -0.62245591]
 [-0.61517874  0.5147624  -0.59713884]
 [-0.33867074 -0.80966534 -0.47931635]
 [-0.52629529 -0.78190408  0.33412466]]
[[-0.96735714 -0.02182641  0.25247529]
 [ 0.73663029 -0.48088687 -0.47552459]
 [-0.27323645  0.12538062  0.95374082]
 [-0.56713774 -0.27178229 -0.77748902]
 [-0.59609459  0.7795

 [-0.59609459  0.7795666   0.19221644]]
[[-0.6831809  -0.04200519  0.72904007]
 [ 0.18289107  0.76098587 -0.62245591]
 [-0.61517874  0.5147624  -0.59713884]
 [-0.33867074 -0.80966534 -0.47931635]
 [-0.52629529 -0.78190408  0.33412466]]
[[-0.96735714 -0.02182641  0.25247529]
 [ 0.73663029 -0.48088687 -0.47552459]
 [-0.27323645  0.12538062  0.95374082]
 [-0.56713774 -0.27178229 -0.77748902]
 [-0.59609459  0.7795666   0.19221644]]
[[-0.6831809  -0.04200519  0.72904007]
 [ 0.18289107  0.76098587 -0.62245591]
 [-0.61517874  0.5147624  -0.59713884]
 [-0.33867074 -0.80966534 -0.47931635]
 [-0.52629529 -0.78190408  0.33412466]]
[[-0.96735714 -0.02182641  0.25247529]
 [ 0.73663029 -0.48088687 -0.47552459]
 [-0.27323645  0.12538062  0.95374082]
 [-0.56713774 -0.27178229 -0.77748902]
 [-0.59609459  0.7795666   0.19221644]]
[[-0.6831809  -0.04200519  0.72904007]
 [ 0.18289107  0.76098587 -0.62245591]
 [-0.61517874  0.5147624  -0.59713884]
 [-0.33867074 -0.80966534 -0.47931635]
 [-0.52629529 -0.781

[[-0.96735714 -0.02192641  0.25247529]
 [ 0.73663029 -0.48088687 -0.47552459]
 [-0.27323645  0.12538062  0.95374082]
 [-0.56713774 -0.27178229 -0.77748902]
 [-0.59609459  0.7795666   0.19221644]]
[[-0.6831809  -0.04200519  0.72904007]
 [ 0.18289107  0.76098587 -0.62245591]
 [-0.61517874  0.5147624  -0.59713884]
 [-0.33867074 -0.80966534 -0.47931635]
 [-0.52629529 -0.78190408  0.33412466]]
[[-0.96735714 -0.02192641  0.25247529]
 [ 0.73663029 -0.48088687 -0.47552459]
 [-0.27323645  0.12538062  0.95374082]
 [-0.56713774 -0.27178229 -0.77748902]
 [-0.59609459  0.7795666   0.19221644]]
[[-0.6831809  -0.04200519  0.72904007]
 [ 0.18289107  0.76098587 -0.62245591]
 [-0.61517874  0.5147624  -0.59713884]
 [-0.33867074 -0.80966534 -0.47931635]
 [-0.52629529 -0.78190408  0.33412466]]
[[-0.96735714 -0.02192641  0.25247529]
 [ 0.73663029 -0.48088687 -0.47552459]
 [-0.27323645  0.12538062  0.95374082]
 [-0.56713774 -0.27178229 -0.77748902]
 [-0.59609459  0.7795666   0.19221644]]
[[-0.6831809  -0.042

[[-0.96735714 -0.02182641  0.25247529]
 [ 0.73663029 -0.48088687 -0.47552459]
 [-0.27333645  0.12538062  0.95374082]
 [-0.56713774 -0.27178229 -0.77748902]
 [-0.59609459  0.7795666   0.19221644]]
[[-0.6831809  -0.04200519  0.72904007]
 [ 0.18289107  0.76098587 -0.62245591]
 [-0.61517874  0.5147624  -0.59713884]
 [-0.33867074 -0.80966534 -0.47931635]
 [-0.52629529 -0.78190408  0.33412466]]
[[-0.96735714 -0.02182641  0.25247529]
 [ 0.73663029 -0.48088687 -0.47552459]
 [-0.27333645  0.12538062  0.95374082]
 [-0.56713774 -0.27178229 -0.77748902]
 [-0.59609459  0.7795666   0.19221644]]
[[-0.6831809  -0.04200519  0.72904007]
 [ 0.18289107  0.76098587 -0.62245591]
 [-0.61517874  0.5147624  -0.59713884]
 [-0.33867074 -0.80966534 -0.47931635]
 [-0.52629529 -0.78190408  0.33412466]]
[[-0.96735714 -0.02182641  0.25247529]
 [ 0.73663029 -0.48088687 -0.47552459]
 [-0.27333645  0.12538062  0.95374082]
 [-0.56713774 -0.27178229 -0.77748902]
 [-0.59609459  0.7795666   0.19221644]]
[[-0.6831809  -0.042

[[-0.6831809  -0.04200519  0.72904007]
 [ 0.18289107  0.76098587 -0.62245591]
 [-0.61517874  0.5147624  -0.59713884]
 [-0.33867074 -0.80966534 -0.47931635]
 [-0.52629529 -0.78190408  0.33412466]]
[[-0.96735714 -0.02182641  0.25247529]
 [ 0.73663029 -0.48088687 -0.47552459]
 [-0.27323645  0.12538062  0.95374082]
 [-0.56713774 -0.27178229 -0.77758902]
 [-0.59609459  0.7795666   0.19221644]]
[[-0.6831809  -0.04200519  0.72904007]
 [ 0.18289107  0.76098587 -0.62245591]
 [-0.61517874  0.5147624  -0.59713884]
 [-0.33867074 -0.80966534 -0.47931635]
 [-0.52629529 -0.78190408  0.33412466]]
[[-0.96735714 -0.02182641  0.25247529]
 [ 0.73663029 -0.48088687 -0.47552459]
 [-0.27323645  0.12538062  0.95374082]
 [-0.56713774 -0.27178229 -0.77758902]
 [-0.59609459  0.7795666   0.19221644]]
[[-0.6831809  -0.04200519  0.72904007]
 [ 0.18289107  0.76098587 -0.62245591]
 [-0.61517874  0.5147624  -0.59713884]
 [-0.33867074 -0.80966534 -0.47931635]
 [-0.52629529 -0.78190408  0.33412466]]
[[-0.96735714 -0.021

 [-0.59609459  0.7795666   0.19221644]]
[[-0.6831809  -0.04210519  0.72904007]
 [ 0.18289107  0.76098587 -0.62245591]
 [-0.61517874  0.5147624  -0.59713884]
 [-0.33867074 -0.80966534 -0.47931635]
 [-0.52629529 -0.78190408  0.33412466]]
[[-0.96735714 -0.02182641  0.25247529]
 [ 0.73663029 -0.48088687 -0.47552459]
 [-0.27323645  0.12538062  0.95374082]
 [-0.56713774 -0.27178229 -0.77748902]
 [-0.59609459  0.7795666   0.19221644]]
[[-0.6831809  -0.04210519  0.72904007]
 [ 0.18289107  0.76098587 -0.62245591]
 [-0.61517874  0.5147624  -0.59713884]
 [-0.33867074 -0.80966534 -0.47931635]
 [-0.52629529 -0.78190408  0.33412466]]
[[-0.96735714 -0.02182641  0.25247529]
 [ 0.73663029 -0.48088687 -0.47552459]
 [-0.27323645  0.12538062  0.95374082]
 [-0.56713774 -0.27178229 -0.77748902]
 [-0.59609459  0.7795666   0.19221644]]
[[-0.6831809  -0.04210519  0.72904007]
 [ 0.18289107  0.76098587 -0.62245591]
 [-0.61517874  0.5147624  -0.59713884]
 [-0.33867074 -0.80966534 -0.47931635]
 [-0.52629529 -0.781

[[-0.96735714 -0.02182641  0.25247529]
 [ 0.73663029 -0.48088687 -0.47552459]
 [-0.27323645  0.12538062  0.95374082]
 [-0.56713774 -0.27178229 -0.77748902]
 [-0.59609459  0.7795666   0.19221644]]
[[-0.6831809  -0.04200519  0.72904007]
 [ 0.18289107  0.76098587 -0.62245591]
 [-0.61527874  0.5147624  -0.59713884]
 [-0.33867074 -0.80966534 -0.47931635]
 [-0.52629529 -0.78190408  0.33412466]]
[[-0.96735714 -0.02182641  0.25247529]
 [ 0.73663029 -0.48088687 -0.47552459]
 [-0.27323645  0.12538062  0.95374082]
 [-0.56713774 -0.27178229 -0.77748902]
 [-0.59609459  0.7795666   0.19221644]]
[[-0.6831809  -0.04200519  0.72904007]
 [ 0.18289107  0.76098587 -0.62245591]
 [-0.61527874  0.5147624  -0.59713884]
 [-0.33867074 -0.80966534 -0.47931635]
 [-0.52629529 -0.78190408  0.33412466]]
[[-0.96735714 -0.02182641  0.25247529]
 [ 0.73663029 -0.48088687 -0.47552459]
 [-0.27323645  0.12538062  0.95374082]
 [-0.56713774 -0.27178229 -0.77748902]
 [-0.59609459  0.7795666   0.19221644]]
[[-0.6831809  -0.042

[[-0.96735714 -0.02182641  0.25247529]
 [ 0.73663029 -0.48088687 -0.47552459]
 [-0.27323645  0.12538062  0.95374082]
 [-0.56713774 -0.27178229 -0.77748902]
 [-0.59609459  0.7795666   0.19221644]]
[[-0.6831809  -0.04200519  0.72904007]
 [ 0.18289107  0.76098587 -0.62245591]
 [-0.61517874  0.5147624  -0.59713884]
 [-0.33867074 -0.80966534 -0.47941635]
 [-0.52629529 -0.78190408  0.33412466]]
[[-0.96735714 -0.02182641  0.25247529]
 [ 0.73663029 -0.48088687 -0.47552459]
 [-0.27323645  0.12538062  0.95374082]
 [-0.56713774 -0.27178229 -0.77748902]
 [-0.59609459  0.7795666   0.19221644]]
[[-0.6831809  -0.04200519  0.72904007]
 [ 0.18289107  0.76098587 -0.62245591]
 [-0.61517874  0.5147624  -0.59713884]
 [-0.33867074 -0.80966534 -0.47941635]
 [-0.52629529 -0.78190408  0.33412466]]
[[-0.96735714 -0.02182641  0.25247529]
 [ 0.73663029 -0.48088687 -0.47552459]
 [-0.27323645  0.12538062  0.95374082]
 [-0.56713774 -0.27178229 -0.77748902]
 [-0.59609459  0.7795666   0.19221644]]
[[-0.6831809  -0.042

 [-0.59609459  0.7795666   0.19221644]]
[[-0.6831809  -0.04200519  0.72904007]
 [ 0.18289107  0.76098587 -0.62245591]
 [-0.61517874  0.5147624  -0.59713884]
 [-0.33867074 -0.80966534 -0.47931635]
 [-0.52629529 -0.78190408  0.33412466]]
[[-0.96735714 -0.02172641  0.25247529]
 [ 0.73663029 -0.48088687 -0.47552459]
 [-0.27323645  0.12538062  0.95374082]
 [-0.56713774 -0.27178229 -0.77748902]
 [-0.59609459  0.7795666   0.19221644]]
[[-0.6831809  -0.04200519  0.72904007]
 [ 0.18289107  0.76098587 -0.62245591]
 [-0.61517874  0.5147624  -0.59713884]
 [-0.33867074 -0.80966534 -0.47931635]
 [-0.52629529 -0.78190408  0.33412466]]
[[-0.96735714 -0.02172641  0.25247529]
 [ 0.73663029 -0.48088687 -0.47552459]
 [-0.27323645  0.12538062  0.95374082]
 [-0.56713774 -0.27178229 -0.77748902]
 [-0.59609459  0.7795666   0.19221644]]
[[-0.6831809  -0.04200519  0.72904007]
 [ 0.18289107  0.76098587 -0.62245591]
 [-0.61517874  0.5147624  -0.59713884]
 [-0.33867074 -0.80966534 -0.47931635]
 [-0.52629529 -0.781

[[-0.6831809  -0.04200519  0.72904007]
 [ 0.18289107  0.76098587 -0.62245591]
 [-0.61517874  0.5147624  -0.59713884]
 [-0.33867074 -0.80966534 -0.47931635]
 [-0.52629529 -0.78190408  0.33412466]]
[[-0.96735714 -0.02182641  0.25247529]
 [ 0.73663029 -0.48088687 -0.47552459]
 [-0.27313645  0.12538062  0.95374082]
 [-0.56713774 -0.27178229 -0.77748902]
 [-0.59609459  0.7795666   0.19221644]]
[[-0.6831809  -0.04200519  0.72904007]
 [ 0.18289107  0.76098587 -0.62245591]
 [-0.61517874  0.5147624  -0.59713884]
 [-0.33867074 -0.80966534 -0.47931635]
 [-0.52629529 -0.78190408  0.33412466]]
[[-0.96735714 -0.02182641  0.25247529]
 [ 0.73663029 -0.48088687 -0.47552459]
 [-0.27313645  0.12538062  0.95374082]
 [-0.56713774 -0.27178229 -0.77748902]
 [-0.59609459  0.7795666   0.19221644]]
[[-0.6831809  -0.04200519  0.72904007]
 [ 0.18289107  0.76098587 -0.62245591]
 [-0.61517874  0.5147624  -0.59713884]
 [-0.33867074 -0.80966534 -0.47931635]
 [-0.52629529 -0.78190408  0.33412466]]
[[-0.96735714 -0.021

 [-0.59609459  0.7795666   0.19221644]]
[[-0.6831809  -0.04200519  0.72904007]
 [ 0.18289107  0.76098587 -0.62245591]
 [-0.61517874  0.5147624  -0.59713884]
 [-0.33867074 -0.80966534 -0.47931635]
 [-0.52629529 -0.78190408  0.33412466]]
[[-0.96735714 -0.02182641  0.25247529]
 [ 0.73663029 -0.48088687 -0.47552459]
 [-0.27323645  0.12538062  0.95374082]
 [-0.56713774 -0.27178229 -0.77738902]
 [-0.59609459  0.7795666   0.19221644]]
[[-0.6831809  -0.04200519  0.72904007]
 [ 0.18289107  0.76098587 -0.62245591]
 [-0.61517874  0.5147624  -0.59713884]
 [-0.33867074 -0.80966534 -0.47931635]
 [-0.52629529 -0.78190408  0.33412466]]
[[-0.96735714 -0.02182641  0.25247529]
 [ 0.73663029 -0.48088687 -0.47552459]
 [-0.27323645  0.12538062  0.95374082]
 [-0.56713774 -0.27178229 -0.77738902]
 [-0.59609459  0.7795666   0.19221644]]
[[-0.6831809  -0.04200519  0.72904007]
 [ 0.18289107  0.76098587 -0.62245591]
 [-0.61517874  0.5147624  -0.59713884]
 [-0.33867074 -0.80966534 -0.47931635]
 [-0.52629529 -0.781

 [-0.52629529 -0.78190408  0.33412466]]
[[-0.96735714 -0.02182641  0.25247529]
 [ 0.73663029 -0.48088687 -0.47552459]
 [-0.27323645  0.12538062  0.95374082]
 [-0.56713774 -0.27178229 -0.77748902]
 [-0.59609459  0.7795666   0.19221644]]
[[-0.6831809  -0.04190519  0.72904007]
 [ 0.18289107  0.76098587 -0.62245591]
 [-0.61517874  0.5147624  -0.59713884]
 [-0.33867074 -0.80966534 -0.47931635]
 [-0.52629529 -0.78190408  0.33412466]]
[[-0.96735714 -0.02182641  0.25247529]
 [ 0.73663029 -0.48088687 -0.47552459]
 [-0.27323645  0.12538062  0.95374082]
 [-0.56713774 -0.27178229 -0.77748902]
 [-0.59609459  0.7795666   0.19221644]]
[[-0.6831809  -0.04190519  0.72904007]
 [ 0.18289107  0.76098587 -0.62245591]
 [-0.61517874  0.5147624  -0.59713884]
 [-0.33867074 -0.80966534 -0.47931635]
 [-0.52629529 -0.78190408  0.33412466]]
[[-0.96735714 -0.02182641  0.25247529]
 [ 0.73663029 -0.48088687 -0.47552459]
 [-0.27323645  0.12538062  0.95374082]
 [-0.56713774 -0.27178229 -0.77748902]
 [-0.59609459  0.779

 [-0.59609459  0.7795666   0.19221644]]
[[-0.6831809  -0.04200519  0.72904007]
 [ 0.18289107  0.76098587 -0.62245591]
 [-0.61507874  0.5147624  -0.59713884]
 [-0.33867074 -0.80966534 -0.47931635]
 [-0.52629529 -0.78190408  0.33412466]]
[[-0.96735714 -0.02182641  0.25247529]
 [ 0.73663029 -0.48088687 -0.47552459]
 [-0.27323645  0.12538062  0.95374082]
 [-0.56713774 -0.27178229 -0.77748902]
 [-0.59609459  0.7795666   0.19221644]]
[[-0.6831809  -0.04200519  0.72904007]
 [ 0.18289107  0.76098587 -0.62245591]
 [-0.61507874  0.5147624  -0.59713884]
 [-0.33867074 -0.80966534 -0.47931635]
 [-0.52629529 -0.78190408  0.33412466]]
[[-0.96735714 -0.02182641  0.25247529]
 [ 0.73663029 -0.48088687 -0.47552459]
 [-0.27323645  0.12538062  0.95374082]
 [-0.56713774 -0.27178229 -0.77748902]
 [-0.59609459  0.7795666   0.19221644]]
[[-0.6831809  -0.04200519  0.72904007]
 [ 0.18289107  0.76098587 -0.62245591]
 [-0.61507874  0.5147624  -0.59713884]
 [-0.33867074 -0.80966534 -0.47931635]
 [-0.52629529 -0.781

[[-0.96735714 -0.02182641  0.25247529]
 [ 0.73663029 -0.48088687 -0.47552459]
 [-0.27323645  0.12538062  0.95374082]
 [-0.56713774 -0.27178229 -0.77748902]
 [-0.59609459  0.7795666   0.19221644]]
[[-0.6831809  -0.04200519  0.72904007]
 [ 0.18289107  0.76098587 -0.62245591]
 [-0.61517874  0.5147624  -0.59713884]
 [-0.33867074 -0.80966534 -0.47921635]
 [-0.52629529 -0.78190408  0.33412466]]
[[-0.96735714 -0.02182641  0.25247529]
 [ 0.73663029 -0.48088687 -0.47552459]
 [-0.27323645  0.12538062  0.95374082]
 [-0.56713774 -0.27178229 -0.77748902]
 [-0.59609459  0.7795666   0.19221644]]
[[-0.6831809  -0.04200519  0.72904007]
 [ 0.18289107  0.76098587 -0.62245591]
 [-0.61517874  0.5147624  -0.59713884]
 [-0.33867074 -0.80966534 -0.47921635]
 [-0.52629529 -0.78190408  0.33412466]]
[[-0.96735714 -0.02182641  0.25247529]
 [ 0.73663029 -0.48088687 -0.47552459]
 [-0.27323645  0.12538062  0.95374082]
 [-0.56713774 -0.27178229 -0.77748902]
 [-0.59609459  0.7795666   0.19221644]]
[[-0.6831809  -0.042

NotImplementedError: 